---
- include: core.yml
  tags: setup-kubernetes-core

- include: storage.yml
  tags: setup-storage-class

- include: helm.yml
  tags: setup-helm
# TODO: why reboot?
- include: ingress.yml
  tags: setup-ingress

- include: calico.yml
  tags: setup-calico

- include: etcd.yml
  tags: setup-etcd
