---
- name: Setup local storage class
  shell: |
    cat << EOF | kubectl apply -f -
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: local-storage
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer
    EOF
  environment:
    KUBECONFIG: "{{ kubernetes_admin_config }}"
