---
- name: Create Persistent Volume PV4
  shell: |
    mkdir -p /mnt/volumes/pv4
    chmod 777 /mnt/volumes/pv4

    cat << EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: local-pv4
    spec:
      capacity:
        storage: 10Gi
      accessModes:
      - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      local:
        path: /mnt/volumes/pv4
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - $HOSTNAME
    EOF

- name: Add Grafana Repository to Helm
  shell: |
    helm repo add grafana \
        https://grafana.github.io/helm-charts
    helm repo update

- name: Deploy Grafana
  shell: |
    helm upgrade -n observability \
        --wait \
        --atomic \
        --create-namespace \
        --set ingress.enabled=true \
        --set ingress.hosts[0]="grafana.kubernetes.local" \
        --set persistence.enabled=true \
        grafana grafana/grafana \
        --install
  timeout: 300

- name: Get Admin Password
  shell: |
    # Get admin password
    kubectl get secret --n observability \
        grafana \
        -o jsonpath="{.data.admin-password}" | \
        base64 --decode ; echo
    register: grafana_pass

- debug:
    var: grafana_pass

# TODO: install dashboard
# 18283
# Example: https://grafana.com/grafana/dashboards/18283-kubernetes-dashboard/

# grafana cli plugins install 18283
