---
- name: Add Jetstack Repository
  shell: |
    helm repo add jetstack https://charts.jetstack.io
    helm repo update

- name: Install Jetstack
  shell: |
    helm install \
      cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --create-namespace \
      --version v1.15.0 \
      --set crds.enabled=true
