---
- name: Create Persistent Volume PV5
  shell: |
    mkdir -p /mnt/volumes/pv5
    chmod 777 /mnt/volumes/pv5

    cat << EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: local-pv5
    spec:
      capacity:
        storage: 10Gi
      accessModes:
      - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      local:
        path: /mnt/volumes/pv5
      nodeAffinity:
        required:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - $HOSTNAME
    EOF

- name: Configure the Chart for our Test environment
  copy:
    src: templates/loki_values.yml
    dest: /tmp/

- name: Deploy Loki
  shell: |
    helm upgrade \
        -n observability \
        --install --atomic --wait \
        --values /tmp/loki_values.yml \
        loki grafana/loki
