---
- name: Deploy Cert Manager
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: selfsigned-cluster-issuer
    spec:
      selfSigned: {}
    EOF

- name: Create CA Certificate
  shell: |
    cat << EOF | kubectl -n cert-manager apply -f -
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: self-signed-ca
    spec:
      isCA: true
      commonName: self-signed-ca
      secretName: self-signed-ca
      issuerRef:
        name: selfsigned-cluster-issuer
        kind: ClusterIssuer
        group: cert-manager.io
    EOF


- name: Create Issuer
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: selfsigned
    spec:
      ca:
        secretName: self-signed-ca
    EOF

